<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <groupId>ar.edu.itba.pod.grpc</groupId>
  <artifactId>grpc-user-parent</artifactId>
  <version>2026.1Q</version>
  <packaging>pom</packaging>
  <name>grpc-user-parent</name>
  <modules>
    <module>api</module>
    <module>server</module>
    <module>client</module>
  </modules>
  <properties>
    <!-- Project -->
    <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    <java.version>25</java.version>
    <!-- Spring gRPC -->
    <spring.grpc.version>1.0.2</spring.grpc.version>
    <spring.boot.version>4.0.4</spring.boot.version>
    <grpc.version>1.77.1</grpc.version>
    <protobuf-java.version>4.33.2</protobuf-java.version>
    <spring-boot.run.skip>true</spring-boot.run.skip>
    <!-- Maven Plugins -->
    <protobuf.maven.version>4.0.3</protobuf.maven.version>
    <maven.assembly.version>3.8.0</maven.assembly.version>
    <maven.compiler.version>3.14.1</maven.compiler.version>
    <maven.source.version>3.4.0</maven.source.version>
    <maven.surefire.version>3.5.4</maven.surefire.version>
  </properties>
  <dependencyManagement>
    <dependencies>
      <dependency>
        <groupId>org.springframework.grpc</groupId>
        <artifactId>spring-grpc-dependencies</artifactId>
        <version>${spring.grpc.version}</version>
        <type>pom</type>
        <scope>import</scope>
      </dependency>
      <dependency>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-dependencies</artifactId>
        <version>${spring.boot.version}</version>
        <type>pom</type>
        <scope>import</scope>
      </dependency>
    </dependencies>
  </dependencyManagement>
  <dependencies>
  </dependencies>
  <build>
    <pluginManagement>
      <plugins>
        <plugin>
          <groupId>org.apache.maven.plugins</groupId>
          <artifactId>maven-assembly-plugin</artifactId>
          <version>${maven.assembly.version}</version>
        </plugin>
        <plugin>
          <groupId>org.springframework.boot</groupId>
          <artifactId>spring-boot-maven-plugin</artifactId>
          <version>${spring.boot.version}</version>
        </plugin>
      </plugins>
    </pluginManagement>
    <plugins>
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-compiler-plugin</artifactId>
        <version>${maven.compiler.version}</version>
        <configuration>
          <verbose>false</verbose>
          <source>${java.version}</source>
          <target>${java.version}</target>
          <encoding>${project.build.sourceEncoding}</encoding>
        </configuration>
      </plugin>
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-source-plugin</artifactId>
        <version>${maven.source.version}</version>
        <executions>
          <execution>
            <phase>package</phase>
            <goals>
              <goal>jar</goal>
            </goals>
          </execution>
        </executions>
      </plugin>
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-surefire-plugin</artifactId>
        <version>${maven.surefire.version}</version>
      </plugin>
    </plugins>
  </build>
</project>